version: '3.8'

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - users_service
      - log_service
    environment:
      SERVICE_PORT: 8080
      USERS_SERVICE_PORT: 8081
      LOG_SERVICE_PORT: 8082
      USERS_SERVICE_HOST: users_service
      LOG_SERVICE_HOST: log_service

  users_service:
    build:
      context: ./users_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SERVICE_PORT: 8081
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: users_db
      DB_HOST: users_db
      DB_PORT: 5432
    depends_on:
      - users_db

  log_service:
    build:
      context: ./log_service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_NAME: log_db
      DB_HOST: log_db
      DB_PORT: 5432
    depends_on:
      - log_db

  users_db:
    image: postgres:13
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  log_db:
    image: postgres:13
    environment:
      POSTGRES_DB: log_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"